on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Abell Website Deployment
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Abell Pages Action
      id: abell-pages
      uses: saurabhdaware/abell-pages-action@master
      with:
        site-path: 'https://github.com/saurabhdaware/abell-readme-layout'
        deploy-branch: 'main'
